# docker-compose.yml

version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    # Set envrionment variables based on the .env file
    env_file:
      - .env
    networks:
      - dissertation_app_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  dissertation_app_network:
    external: true